root: true
extends:
  - stylelint-config-standard
  - stylelint-config-standard-scss
  - stylelint-config-recommended-vue
  - stylelint-config-recommended-vue/scss
plugins:
  - stylelint-prettier
rules:
  'prettier/prettier': true
